Breakpoint 1 at 0x4004f1: file src/ptest/example_python_debug.cpp, line 14.

Breakpoint 1, main () at src/ptest/example_python_debug.cpp:14
14	  return (0);
test_add_func (__main__.Test)
This test case tests add method ... ok
test_is_odd_func (__main__.Test)
isOddメソッドのテストケースです ... ok
test_make_pair_struct (__main__.Test)
This test case tests make_pair struct ... ok

----------------------------------------------------------------------
Ran 3 tests in 13.453s

OK
